# AdGuard Home port redirect: 53 -> 5335
rdr pass on lo0 proto {tcp, udp} from any to YOUR_LOCAL_IP port 53 -> YOUR_LOCAL_IP port 5335
rdr pass on en0 proto {tcp, udp} from any to YOUR_LOCAL_IP port 53 -> YOUR_LOCAL_IP port 5335
rdr pass on en1 proto {tcp, udp} from any to YOUR_LOCAL_IP port 53 -> YOUR_LOCAL_IP port 5335
